### ISSUE TITLE
synapse server can not restart after homeserver.yaml updated

### ISSUE THREAD

**Issue by NewOcean11** [matrix-org/synapse-auto-accept-invite#13]
install & updated yaml according to instruction,then restart synapse
then always got message like
--Job for matrix-synapse.service failed because the control process exited with error code.
--See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.

just wonder why?

**Comment by lennartbrandin** [comment]
For a more detailed status you should use:

```
systemctl status matrix-synapse.service
```

**Comment by NewOcean11** [comment]
> For a more detailed status you should use:
> 
> ```
> systemctl status matrix-synapse.service
> ```

root@racknerd-tq7109:~# systemctl status matrix-synapse.service
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-10-11 08:34:20 BST; 2s ago
    Process: 414685 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config->
    Process: 414731 ExecStart=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-pat>
   Main PID: 414731 (code=exited, status=1/FAILURE)

 ....what i get...

**Comment by lennartbrandin** [comment]
You can use `journalctl -u matrix-synapse` for the complete log, press <kbd>G</kbd> to jump to the end.

Also please use codeblocks for commands/code/logfiles.

**Comment by DMRobertson** [comment]
To be able to help you, we need

- meaningful logs, covering the the time period between starting Synapse and it producing the error message
- to know which Synapse version you are using and how you installed it
- to know which `synapse-auto-accept-invite` version you are using and how you installed it.

**Comment by reivilibre** [comment]
Note: `journalctl -eu matrix-synapse` will take you straight to the bottom of the logs, which is useful when trying to see why it's not starting up.
It would be useful to know what your changes were.

**Comment by DMRobertson** [comment]
I'm going to close this, since we can't help you without logs. @NewOcean11: please re-open if you manage to get logs.
