### ISSUE TITLE
Autoinvite not working with federations

### ISSUE THREAD

**Issue by dzondrak** [matrix-org/synapse-auto-accept-invite#18]
Hello, I experienced an issue when I was trying to test autonvite with two federations, there is a problem when the room is in a partial state but host is't stored in partial_state_rooms_servers for this room, which ends "Host not in room" error. 
Steps to reproduce:

0. element-web
1. two federations with autoinvite enabled, with no workers enabled
2. on 1 federation, invite user from 2 federation to 1-1 room
3. on 2 federation there is an information that user 2 joined the room and an infinite circle progress bar and unable to send any message

I will analyze this further but maybe someone knows something to help me, so that I don't have to reinvent the wheel:)

**Comment by sandhose** [comment]
This looks like it's an issue on the Synapse side, which should be fixed with https://github.com/element-hq/synapse/pull/16973
