### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by unclejay80** [matrix-org/synapse-auto-accept-invite#4]
**Describe the bug**
It is not possible to install using `pip install synapse-auto-accept-invite` because not py file is inside the deployed image

At  https://pypi.org/project/synapse-auto-accept-invite/#files  the download of the tar.gz
https://files.pythonhosted.org/packages/c2/69/a857a8b872fb58fc01f885e2c3cc99bd6a393ad3e394e617d4d3313f1b25/synapse_auto_accept_invite-1.0.1.tar.gz

doesn't contain any source code

**Comment by dklimpel** [comment]
This works for me:
```bash
pip install synapse-auto-accept-invite
Collecting synapse-auto-accept-invite
  Downloading synapse_auto_accept_invite-1.0.1-py3-none-any.whl (5.9 kB)
Installing collected packages: synapse-auto-accept-invite
Successfully installed synapse-auto-accept-invite-1.0.1
```

**Comment by clokep** [comment]
Does it break with `pip install synapse-auto-accept-invite --no-binary`? Maybe the source distribution was broken?

**Comment by unclejay80** [comment]
was a mistake of myself, sorry for bothering you
